//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveIT.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class cijena
    {
        public int vozilo { get; set; }
        public decimal nabavna_bez_pdv { get; set; }
        public Nullable<decimal> nabavna_sa_pdv { get; set; }
        public decimal osnovica { get; set; }
        public decimal porez { get; set; }
        public decimal prodajna_sa_pdv { get; set; }
        public decimal marza { get; set; }
        public decimal popravci_interni { get; set; }
        public decimal popravci_ekterni { get; set; }
        public System.DateTime datum_izracuna { get; set; }
        public int tip_poreza_nabavna { get; set; }
        public int tip_poreza_prodajna { get; set; }
    
        public virtual tip_poreza tip_poreza { get; set; }
        public virtual tip_poreza tip_poreza1 { get; set; }
        public virtual vozilo vozilo1 { get; set; }
    }
}
