//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveIT.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class dio
    {
        public int id_dio { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public Nullable<int> kolicina { get; set; }
        public Nullable<int> cijena { get; set; }
        public int nalog { get; set; }
    
        public virtual nalog_za_servis nalog_za_servis { get; set; }
    }
}
