//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveIT.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnik
    {
        public korisnik()
        {
            this.nalog_za_servis = new HashSet<nalog_za_servis>();
        }
    
        public int id_korisnik { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
        public string email { get; set; }
        public int tip_korisnika { get; set; }
    
        public virtual tip_korisnika tip_korisnika1 { get; set; }
        public virtual ICollection<nalog_za_servis> nalog_za_servis { get; set; }
    }
}
