//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveIT.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class kupac
    {
        public kupac()
        {
            this.ugovor = new HashSet<ugovor>();
        }
    
        public int id_kupac { get; set; }
        public int tip_kupca { get; set; }
    
        public virtual tip_kupca tip_kupca1 { get; set; }
        public virtual ICollection<ugovor> ugovor { get; set; }
    }
}
