//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveIT.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class nalog_za_servis
    {
        public int id_nalog_za_servis { get; set; }
        public string opis { get; set; }
        public int vozilo { get; set; }
        public int korisnik { get; set; }
    
        public virtual korisnik korisnik1 { get; set; }
        public virtual vozilo vozilo1 { get; set; }
    }
}
