//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveIT.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class parking
    {
        public parking()
        {
            this.vozilo = new HashSet<vozilo>();
        }
    
        public int id_parking { get; set; }
        public string naziv { get; set; }
        public Nullable<int> kapacitet { get; set; }
    
        public virtual ICollection<vozilo> vozilo { get; set; }
    }
}
