//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveIT.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class slika_vozilo
    {
        public int idslika_vozilo { get; set; }
        public string path { get; set; }
        public int vozilo { get; set; }
    
        public virtual vozilo vozilo1 { get; set; }
    }
}
