//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveIT.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ugovor
    {
        public int id_ugovor { get; set; }
        public int kupac { get; set; }
        public int vozilo { get; set; }
        public System.DateTime datum { get; set; }
        public int dobavljac_iddobavljac { get; set; }
    
        public virtual dobavljac dobavljac { get; set; }
        public virtual kupac kupac1 { get; set; }
        public virtual vozilo vozilo1 { get; set; }
    }
}
