//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveIT.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vozilo
    {
        public vozilo()
        {
            this.dobavljac = new HashSet<dobavljac>();
            this.nalog_za_servis = new HashSet<nalog_za_servis>();
            this.slika_vozilo = new HashSet<slika_vozilo>();
            this.ugovor = new HashSet<ugovor>();
            this.dodatna_oprema = new HashSet<dodatna_oprema>();
        }
    
        public int id_vozilo { get; set; }
        public string sasija { get; set; }
        public Nullable<System.DateTime> datum_prve_registracije { get; set; }
        public string boja { get; set; }
        public int godina_proizvodnje { get; set; }
        public Nullable<System.DateTime> datum_nabavke { get; set; }
        public int snaga_kw { get; set; }
        public int sjedista { get; set; }
        public Nullable<int> nosivost { get; set; }
        public string registracija { get; set; }
        public string prometna { get; set; }
        public string servisna { get; set; }
        public int kilometri { get; set; }
        public int tip_vozila { get; set; }
        public int model_vozila { get; set; }
        public int parking { get; set; }
    
        public virtual cijena cijena { get; set; }
        public virtual ICollection<dobavljac> dobavljac { get; set; }
        public virtual model_vozila model_vozila1 { get; set; }
        public virtual ICollection<nalog_za_servis> nalog_za_servis { get; set; }
        public virtual parking parking1 { get; set; }
        public virtual ICollection<slika_vozilo> slika_vozilo { get; set; }
        public virtual tip_vozila tip_vozila1 { get; set; }
        public virtual ICollection<ugovor> ugovor { get; set; }
        public virtual ICollection<dodatna_oprema> dodatna_oprema { get; set; }
    }
}
